### ISSUE TITLE
Pull requests ?

### ISSUE THREAD

**Issue by wecurse** [melMass/vscode-vex#5]
Many thanks for putting this together @melMass!
I'm also looking to extend the currently available list of functions ( #4 )

Do you accept pull requests or should I fork and make my own?

Let me know

Sven

**Comment by melMass** [comment]
Hi,

Thanks for your interest in contributing! 
I would be more than happy to review any pull request for this project.
I think it's better if we all work together on the same codebase rather than making zillions forks.
Thanks to you I've just discovered the new issues, I had trouble with notifications apparently.

**Comment by melMass** [comment]
@wecurse By any chance have you added new functions? I'm going to update this repo version on the weekend I can implement yours at the same time.
